# Generated by Django 5.2.2 on 2025-06-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='photos/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
