# Generated by Django 5.2.1 on 2025-06-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0003_remove_math_a_remove_math_b_remove_math_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='math',
            name='a',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='math',
            name='operation',
            field=models.CharField(default='+', max_length=10),
            preserve_default=False,
        ),
    ]
