# Generated by Django 5.2.1 on 2025-06-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0004_math_a_math_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='math',
            name='b',
            field=models.IntegerField(default=0),
        ),
    ]
