# Generated by Django 5.2.1 on 2025-06-05 17:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0005_math_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='math',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
