# Generated by Django 5.2.2 on 2025-06-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0006_math_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='math',
            options={'ordering': ['-id']},
        ),
    ]
